apiVersion: apps/v1
kind: Deployment
metadata:
  name: katas-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: katas-app
  template:
    metadata:
      labels:
        app: katas-app
    spec:
      containers:
        - name: katas-app
          image: katas-app:v1.0
          ports:
            - containerPort: 8000
          env:
            - name: FIRST_VERSION
              value: "v1.0"
            - name: FIRST_CLIENT
              value: "client-a"
